version: "3.9"

services:

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - "./Moneyes.Server/.env"
    ports:
      - "80:80"
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      context: ./Moneyes.Server
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t