version: "3.9"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/ssl/:/etc/nginx/ssl/
  authserver:
    depends_on:
      - nginx
      - db
    build:
      context: ./Moneyes.Server
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file:
      - ./.env
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    env_file:
      - ./.env
    environment:
        ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    volumes:
      - /var/opt/moneyes-docker/mssql/data:/var/opt/mssql/data